travis:
  secure:
    BINSTAR_TOKEN: mD/IMEoyknbe0KlrvflVGgbLxCvOzCmLx08BQ3FV7c0P0pYaAPCB4DNKSCBV0ESjXJF9DqwXgfw2Q92l73Vlv3pYroY0bF7641wzLF2N4UUWBv+ZrZiXiceemNF3jTLBNHFaxw1DtRmZNqAb8LtblDivwRtHDwlsRtwwIz/5FvFVqRPmverRLch8OPi7d3/CL43OfphnA3VQ3SjLfbQgoIOTiqBF2ndfYvMsd2F3otNNI8SlKpmMLhJ2nMa+RPSrNS9MX0Z8pR0A/RKYEdQSv/UuG8evxpj6jxoj8WhiPv1ns2jR6jy1jj0cepBcMurgODFpj8tHpX0hGim7M2VkYzSqfDR4nL+MdRKL8+9w/9a8p7iFTRVxLu2dQMtQrLhYxfVbOeji9jasADlR75fnuyPROEy2aJ5LtqRJJrCSHU3/jIxqjQvm4tMduSNttJas+AdqGpealHi0VMorVf+qkuP5zLKYBIgdQLXntfGYBUeY0OgCLwrS+sQPSSQ1v0Nl1RVHRCyw1WJW3L+CFFzSPpgREH9ATU6prtc31Cm5mrb4yQGjVovyd4BQy4Ench00oJP5vklG6Z494SZbCMr5EPeLDoCmwz0gXPnyiA1rGwVcN7AcJXbaxst3DKIDi0RW+0QU4hG0z+p24Fup5jNlYOVbfRfCSvJEHlbTQR58jus=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
